# Generated by Django 5.2.1 on 2025-05-11 15:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image for the product.', null=True, upload_to=api.models.product_main_image_path),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the product gallery.', upload_to=api.models.product_gallery_image_path)),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for the image (for accessibility and SEO).', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as a featured image in the gallery (if applicable).')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.product')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
