# Generated by Django 5.2.1 on 2025-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_availability_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as a featured product.'),
        ),
    ]
